#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GROMACS include-topology writer for :class:`~mdinterface.core.specie.Specie`.

Writes ``[ atomtypes ]``, ``[ moleculetype ]``, ``[ atoms ]``, ``[ bonds ]``,
``[ angles ]``, and ``[ dihedrals ]`` sections in GROMACS ITP format with the
appropriate unit conversions from LAMMPS *real* units.

Unit conversions
----------------
- Energy  : kcal/mol → kJ/mol  (× 4.184)
- Length  : Å → nm             (× 0.1)
- Bond kr : kcal/mol/Å² → kJ/mol/nm²   (× 418.4)
- Angle kr: kcal/mol/rad² → kJ/mol/rad² (× 4.184)

OPLS-AA proper dihedrals are split into up to four ``funct=9`` terms.
LAMMPS cvff improper dihedrals are mapped to ``funct=4``.
"""

import logging
import os

logger = logging.getLogger(__name__)

#%%

# unit conversion factors
_KCAL_TO_KJ = 4.184
_ANG_TO_NM  = 0.1

# ---------------------------------------------------------------------------
# Column format strings -- header and data share the same field widths so
# that labels sit directly above their values.  Both lines start with a
# 2-character prefix ("; " for headers, "  " for data rows).  Explicit
# 2-space gaps between every column prevent adjacent fields from touching.
#
# The name/type column width (nw) is computed dynamically inside
# write_gromacs_itp from the actual longest atom type label so that short
# molecules don't get unnecessary whitespace.
# ---------------------------------------------------------------------------

def _at_hdr(nw):
    return f"; {{:<{nw}}}  {{:>6}}  {{:>9}}  {{:>8}}  {{:<5}}  {{:>12}}  {{:>14}}\n"

def _at_fmt(nw):
    return f"  {{:<{nw}}}  {{:>6d}}  {{:>9.4f}}  {{:>8.4f}}  {{:<5}}  {{:>12.6f}}  {{:>14.6f}}\n"

def _atoms_hdr(nw):
    return f"; {{:>6}}  {{:<{nw}}}  {{:>5}}  {{:<6}}  {{:<6}}  {{:>4}}  {{:>12}}  {{:>10}}\n"

def _atoms_fmt(nw):
    return f"  {{:>6d}}  {{:<{nw}}}  {{:>5d}}  {{:<6}}  {{:<6}}  {{:>4d}}  {{:>12.6f}}  {{:>10.5f}}\n"

# [ bonds ]  ai(5R)  aj(5R)  funct(5R)  b0(12R,.6f)  kb(16R,.4f)
_BONDS_HDR = "; {:>5}  {:>5}  {:>5}  {:>12}  {:>16}\n"
_BONDS_FMT = "  {:>5d}  {:>5d}  {:>5d}  {:>12.6f}  {:>16.4f}\n"

# [ angles ]  ai(5R)  aj(5R)  ak(5R)  funct(5R)  th0(12R,.4f)  cth(16R,.4f)
_ANGS_HDR  = "; {:>5}  {:>5}  {:>5}  {:>5}  {:>12}  {:>16}\n"
_ANGS_FMT  = "  {:>5d}  {:>5d}  {:>5d}  {:>5d}  {:>12.4f}  {:>16.4f}\n"

# [ dihedrals ]  ai(5R)  aj(5R)  ak(5R)  al(5R)  funct(5R)  phi0(10R,.3f)  kphi(14R,.6f)  n(3R)
_DIHS_HDR  = "; {:>5}  {:>5}  {:>5}  {:>5}  {:>5}  {:>10}  {:>14}  {:>3}\n"
_DIHS_FMT  = "  {:>5d}  {:>5d}  {:>5d}  {:>5d}  {:>5d}  {:>10.3f}  {:>14.6f}  {:>3d}\n"


def write_gromacs_itp(specie, filename=None):
    """
    Write a GROMACS include topology (.itp) file for a Specie.

    .. warning::
        GROMACS output is **experimental**.  Unit conversions and dihedral
        mappings have been validated for OPLS-AA molecules generated by
        LigParGen, but other force fields or atom styles may need adjustments.
        Use with care and verify the output against a reference.

    Parameters
    ----------
    specie : Specie
        The molecular species to write.
    filename : str, optional
        Output filename. Defaults to ``{resname}.itp``.
    """
    logger.warning(
        "write_gromacs_itp is experimental -- verify output before production use."
    )
    if filename is None:
        filename = f"{specie.resname}.itp"

    masses   = specie.atoms.get_masses()
    charges  = specie.atoms.get_initial_charges()
    atnums   = specie.atoms.get_atomic_numbers()
    atom_types, type_indexes = specie.get_atom_types(return_index=True)

    bond_idxs,  bond_tids  = specie.bonds
    angle_idxs, angle_tids = specie.angles
    dih_idxs,   dih_tids   = specie.dihedrals
    imp_idxs,   imp_tids   = specie.impropers

    # column width for name/type: fit the longest label, at least "name" (4)
    nw = max(max(len(t) for t in atom_types), 4)

    AT_HDR    = _at_hdr(nw)
    AT_FMT    = _at_fmt(nw)
    ATOMS_HDR = _atoms_hdr(nw)
    ATOMS_FMT = _atoms_fmt(nw)

    with open(filename, "w") as f:
        f.write("; GROMACS ITP file generated by mdinterface\n")
        f.write(f"; Molecule: {specie.resname}\n\n")

        # ------------------------------------------------------------------
        # [ atomtypes ] -- unique FF types with LJ parameters
        # ------------------------------------------------------------------
        f.write("[ atomtypes ]\n")
        f.write(AT_HDR.format(
            "name", "atnum", "mass", "charge", "ptype", "sigma(nm)", "eps(kJ/mol)"))
        seen = set()
        for atype, atnum, mass, tidx in zip(
                atom_types, atnums, masses, type_indexes):
            if atype in seen:
                continue
            seen.add(atype)
            stype = specie._stype[tidx]
            sig = (stype.sig * _ANG_TO_NM) if stype.sig is not None else 0.0
            eps = (stype.eps * _KCAL_TO_KJ) if stype.eps is not None else 0.0
            f.write(AT_FMT.format(atype, atnum, mass, 0.0, "A", sig, eps))
        f.write("\n")

        # ------------------------------------------------------------------
        # [ moleculetype ]
        # ------------------------------------------------------------------
        f.write("[ moleculetype ]\n")
        f.write("; name      nrexcl\n")
        f.write(f"  {specie.resname:<10s}  3\n\n")

        # ------------------------------------------------------------------
        # [ atoms ]
        # ------------------------------------------------------------------
        f.write("[ atoms ]\n")
        f.write(ATOMS_HDR.format(
            "nr", "type", "resnr", "residu", "atom", "cgnr", "charge", "mass"))
        for ii, (atype, charge, mass, sid) in enumerate(
                zip(atom_types, charges, masses, specie._sids)):
            atom_name = sid.split("_")[0]
            f.write(ATOMS_FMT.format(
                ii+1, atype, 1, specie.resname, atom_name, ii+1, charge, mass))
        f.write("\n")

        # ------------------------------------------------------------------
        # [ bonds ]
        # ------------------------------------------------------------------
        if bond_idxs:
            f.write("[ bonds ]\n")
            f.write(_BONDS_HDR.format("ai", "aj", "funct", "b0(nm)", "kb(kJ/mol/nm2)"))
            for (ai, aj), tid in zip(bond_idxs, bond_tids):
                bond = specie._btype[tid]
                b0 = (bond.r0 * _ANG_TO_NM)                    if bond.r0 is not None else 0.0
                # LAMMPS: E = K*(r-r0)^2  |  GROMACS: V = (kb/2)*(r-r0)^2  => kb = 2*K
                kb = (2 * bond.kr * _KCAL_TO_KJ / _ANG_TO_NM**2) if bond.kr is not None else 0.0
                f.write(_BONDS_FMT.format(ai+1, aj+1, 1, b0, kb))
            f.write("\n")

        # ------------------------------------------------------------------
        # [ angles ]
        # ------------------------------------------------------------------
        if angle_idxs:
            f.write("[ angles ]\n")
            f.write(_ANGS_HDR.format("ai", "aj", "ak", "funct", "th0(deg)", "cth(kJ/mol/rad2)"))
            for (ai, aj, ak), tid in zip(angle_idxs, angle_tids):
                angle = specie._atype[tid]
                th0 = angle.theta0                          if angle.theta0 is not None else 0.0
                # LAMMPS: E = K*(θ-θ0)^2  |  GROMACS: V = (kt/2)*(θ-θ0)^2  => kt = 2*K
                cth = (2 * angle.kr * _KCAL_TO_KJ)         if angle.kr    is not None else 0.0
                f.write(_ANGS_FMT.format(ai+1, aj+1, ak+1, 1, th0, cth))
            f.write("\n")

        # ------------------------------------------------------------------
        # [ dihedrals ] -- proper (OPLS Fourier -> funct=9)
        #
        # LAMMPS: E = (K1/2)(1+cos φ) + (K2/2)(1-cos 2φ)
        #           + (K3/2)(1+cos 3φ) + (K4/2)(1-cos 4φ)
        # GROMACS funct=9: V = kphi * (1 + cos(n*phi - phi0))
        #   K1 -> n=1, phi0=0,   kphi = K1/2
        #   K2 -> n=2, phi0=180, kphi = K2/2
        #   K3 -> n=3, phi0=0,   kphi = K3/2
        #   K4 -> n=4, phi0=180, kphi = K4/2
        # ------------------------------------------------------------------
        if dih_idxs:
            f.write("[ dihedrals ]\n")
            f.write("; proper dihedrals -- OPLS Fourier series, funct=9\n")
            f.write(_DIHS_HDR.format("ai", "aj", "ak", "al", "funct", "phi0(deg)", "kphi(kJ/mol)", "n"))
            opls_map = [(0, 1, 0.0), (1, 2, 180.0),
                        (2, 3, 0.0), (3, 4, 180.0)]
            for (ai, aj, ak, al), tid in zip(dih_idxs, dih_tids):
                dih  = specie._dtype[tid]
                vals = dih.values  # [K1, K2, K3, K4, K5?]
                for vi, n, phi0 in opls_map:
                    K = vals[vi]
                    if K is None or K == 0.0:
                        continue
                    kphi = K / 2.0 * _KCAL_TO_KJ
                    f.write(_DIHS_FMT.format(ai+1, aj+1, ak+1, al+1, 9, phi0, kphi, n))
            f.write("\n")

        # ------------------------------------------------------------------
        # [ dihedrals ] -- improper (LAMMPS cvff -> funct=4)
        #
        # LAMMPS: E = K(1 + d*cos(n*phi))
        # GROMACS funct=4: V = kphi(1 + cos(n*psi - psi0))
        #   d= 1 -> psi0=0
        #   d=-1 -> psi0=180
        # ------------------------------------------------------------------
        if imp_idxs:
            f.write("[ dihedrals ]\n")
            f.write("; improper dihedrals, funct=4\n")
            f.write(_DIHS_HDR.format("ai", "aj", "ak", "al", "funct", "phi0(deg)", "kphi(kJ/mol)", "n"))
            for (ai, aj, ak, al), tid in zip(imp_idxs, imp_tids):
                imp      = specie._itype[tid]
                K, d, n  = imp.values
                phi0 = 0.0 if d == 1 else 180.0
                kphi = (K * _KCAL_TO_KJ) if K is not None else 0.0
                f.write(_DIHS_FMT.format(ai+1, aj+1, ak+1, al+1, 4, phi0, kphi, n))
            f.write("\n")

    logger.debug("Wrote GROMACS ITP: %s", filename)


def write_gromacs_top(universe, itp_files, filename="system.top",
                      system_name="MD System"):
    """
    Write a GROMACS system topology (.top) file.

    Parameters
    ----------
    universe : mda.Universe
        The assembled system (after SimCell.build()).  Used to determine
        molecule counts from ``universe.residues``.
    itp_files : list of str
        Basenames of the per-species ITP files to ``#include``.
    filename : str, optional
        Output filename. Default ``"system.top"``.
    system_name : str, optional
        Title written in the ``[ system ]`` section.
    """
    # Preserve the order molecules appear in the GRO/universe so that
    # [ molecules ] matches the coordinate file exactly.
    seen = {}
    for res in universe.residues:
        name = res.resname
        seen[name] = seen.get(name, 0) + 1

    with open(filename, "w") as f:
        f.write("; GROMACS topology file generated by mdinterface\n\n")

        # OPLS-AA defaults: LJ (nbfunc=1), geometric combining (comb-rule=3)
        f.write("[ defaults ]\n")
        f.write("; nbfunc  comb-rule  gen-pairs  fudgeLJ  fudgeQQ\n")
        f.write("  1       3          yes        0.5      0.5\n\n")

        for itp in itp_files:
            f.write(f'#include "{itp}"\n')
        f.write("\n")

        f.write("[ system ]\n")
        f.write(f"{system_name}\n\n")

        f.write("[ molecules ]\n")
        f.write("; {:<14}  {:>6}\n".format("molecule", "nmols"))
        for resname, count in seen.items():
            f.write(f"  {resname:<14s}  {count:>6d}\n")

    logger.debug("Wrote GROMACS TOP: %s", filename)
